version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./docker/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    depends_on:
      - server
      - db
  server:
    image: caddy:2.4.5-alpine
    volumes:
      - .:/app
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:80
  db:
    image: postgres:9.6.23-alpine3.14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  db-data:
    driver: local
