version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app:z
      - ./docker/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf:z
    depends_on:
      - server
      - db
  server:
    image: caddy:2.4.5-alpine
    volumes:
      - .:/app:z
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:z
    ports:
      - 8080:80
  db:
    image: mysql:8.0.27
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

volumes:
  db:
    driver: local
